[package]
name = "egldvoting"
version = "0.0.1"
authors = [ "you",]
edition = "2021"
publish = false

[lib]
path = "src/egldvoting.rs"

[dependencies.elrond-wasm]
version = "0.36.1"

[dev-dependencies.elrond-wasm-debug]
version = "0.36.1"
